# Generated by Django 3.1.5 on 2021-01-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20210104_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='On Queue', editable=False, max_length=9),
        ),
    ]
