# Generated by Django 3.1.5 on 2021-02-18 13:32

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shops.models
import shops.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('is_owner', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='default_avatar.jpg', upload_to=shops.models.pic_name)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, to='shops.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(upload_to=shops.models.file_name, validators=[shops.validators.validate_file_extension])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, default='', max_length=300)),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], default='A4', max_length=9)),
                ('status', models.CharField(choices=[('On Queue', 'On Queue'), ('Proccessing', 'Proccessing'), ('Finished', 'Finished'), ('Recieved', 'Recieved')], default='On Queue', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='shops.profile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shops.shop')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='printtype', to='shops.type')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
