# Generated by Django 3.1.5 on 2021-01-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isOwner',
            new_name='is_owner',
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, to='shops.profile'),
        ),
    ]
